version: '3.9'
services:
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '80:80'
    depends_on:
      - nuxt
  nuxt:
      container_name: nuxt
      build:
        context: ./
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      ports:
        - '3000:3000'
      restart: always